import Head from "next/head";
import React, { useState, useEffect } from "react";
import Image from "next/image";

import styles from "../styles/Home.module.scss";
import Maincontent from "../components/Maincontent";
import Sidebar from "../components/Sidebar";
import ContentStickyHeader from "../components/ContentStickyHeader";
import icon from "../public/favicon.ico";
export default function Home() {
  const [toggleSide, settoggleSide] = useState(false);

  const [switchsides, setswitchsides] = useState("unset");
  useEffect(() => {
    const scrollUp = document.getElementById("scrollToTop");
    window.addEventListener("scroll", () => {
      if (window.scrollY >= 400) {
        scrollUp.style.right = "3%";
        return;
      } else {
        scrollUp.style.right = "-13%";
      }
    });
  }, []);
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.homeCarousel}></div>
        <ContentStickyHeader
          settoggleSide={settoggleSide}
          switchsides={switchsides}
          toggleSide={toggleSide}
        />
        <div className={styles.contentContainer}>
          <Sidebar
            toggleSide={toggleSide}
            setswitchsides={setswitchsides}
            switchsides={switchsides}
          />
          <Maincontent switchsides={switchsides} />
        </div>
        <a href="#" id="scrollToTop" className={styles.scrollToTop}>
          <Image src={icon} />
        </a>
      </main>
    </div>
  );
}
